### ISSUE TITLE
is "loading from bitarray" supported?

### ISSUE THREAD

**Issue by richtier** [dsummersl/bloomfilters#3]
I have a bloom filter server side, for which I can get the internal bit array.

I would like to load this bit array into the frontend bloomfilter.

I see I can slice the bit array, and then set the `slices` property of the `SlicesBloomFilter`.

Before I do this, is there a more "built in" way of doing this?

**Comment by dsummersl** [comment]
The simplest thing to do is use `JSON.serialize()`. See the unit tests for an example (https://github.com/dsummersl/bloomfilters/blob/master/test/spec/bloomfilterspec.coffee#L130).

I've discussed in the past adding more examples of bson/messagepack/JSON.serialize examples. That kind of thing of interest?

**Comment by richtier** [comment]
sorry I did not make my use case clear enough: the server side bloom filter code is python. The python bloom filter will provide the bit array as a super long string that looks like `'010010010010000001...'`.

I would like to "populate" the client side `BloomFilter` with `'010010010010000001...'`.

Is this possible?

**Comment by dsummersl** [comment]
Ah...I see. It sounds like your python implementation is not a sliced bloom filter, just a plain vanilla bloom filter? That in itself isn't much of a problem in that you could setup a `SlicedBloomFilter` with the # of slices equal to 1.

The main problem here really is the hashing function. The `HashGenerator` used in this library is built to minimize the number of `sha1` calls for performance reasons, and its not pluggable. You will need to match the hashing implementation in python.

We could definitely make the hash generator pluggable - you could then make your own hashing function to match the behavior of your python library.

**Comment by richtier** [comment]
very good points. thanks.

**Comment by dsummersl** [comment]
If you figure out your path lemme know if I can do anything - happy to make the requisite change or accept PRs.

**Comment by richtier** [comment]
after a bit of experimentation I abandoned the idea of populating the bloomfilter using python and passing the bitarray to the browser - there would be too much work required to add parity between existing python bloom filters and javascript implementations.

Instead I will make a javascript microservice that uses the same blooom filter implementation as the browser, and the values will be passed from python (django) code to the javascript service using a queue. This will simplify things a lot :)

**Comment by dsummersl** [comment]
Quite! Glad you figured it out and thanks for the update.
